account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    #previous login views
    #path('login/', views.user_login, name='login'),
    
    #LoginView LogoutView view of Django's authentication framework
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.dashboard, name='dashboard'),
    
    #change password urls (using Django authentication views)
    #PasswordChangeView will handle the form to change the password
    path('password_change/', auth_views.PasswordChangeView.as_view(),name='password_change'),
    # will display a success message for password changed
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    #reset password urls
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
    path('register/', views.register, name='register'),
    
    path('edit/', views.edit, name='edit'),
    
    path('users/', views.user_list, name='user_list'),
    path('users/follow/', views.user_follow,name='user_follow'),
    path('users/<username>/', views.user_detail, name='user_detail'),
]

bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images'))
]

if settings.DEBUG:  #that is when the DEBUG setting is set to True 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path 
from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
    path('ranking/', views.image_ranking, name='create'),
]

account/models.py
from django.db import models
from django.conf import settings
from django.db.models.fields import related
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    #The user one-to-one field allows you	to associate profiles with users.
    #use CASCADE for the on_delete	parameter so that its related profile also	gets deleted when a	user is	deleted.
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    #install the Pilloe library to handle images.  (pip install Pillow==5.1.0)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)

    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

class Contact(models.Model):
    #user_from - for user that creates relationship,
    user_from = models.ForeignKey('auth.User', related_name='rel_from_set', on_delete=models.CASCADE)
    #user_to - for the user being followed
    user_to = models.ForeignKey('auth.User', related_name='rel_to_set', on_delete=models.CASCADE)
    #to store the time when relationship was created
    created = models.DateTimeField(auto_now_add=True, db_index=True)    #db_index is true to create db index for created field
   
    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} follows {}'.format(self.user_from, self.user_to)

following = models.ManyToManyField('self', through=Contact, related_name='followers', symmetrical=False)
#This	is	a	many-to-many	relationship	from	the	User model	to	itself:	we	refer	to	'self'	in	the	ManyToManyField	field	to	create	a
# relationship	to	the	same	model.

#add following field to user dynamically ,  symmetrical=False to define	a	non-symmetric relation.
User.add_to_class('following', models.ManyToManyField('self', through=Contact, related_name='followers', symmetrical=False))
    

account/forms.py
from django import forms
from django.db import models
from django.forms import fields
from django.contrib.auth.models import User
from .models import Profile

#login form using Django authentication framework
#this form willbe used to authenticate users against databse
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    #passwordInput widget to render its html input element

#sign up form to allow user registration on website
class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        #to check if the both passwords are same or not
        if cd['password'] != cd['password2'] :
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

class UserEditForm(forms.ModelForm): #to edit their profile, which r attributes of built-in Django user model
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm): #to edit their profile, which r attributes of built-in custom profile model
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

account/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm
from django.contrib.auth.decorators import login_required
from .models import Profile, Contact
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.decorators.http import require_POST
from common.decorators import ajax_required
from actions.utils import create_action
from actions.models import Action

# Create your views here.
def user_login(request):  #user login view is called with a get request
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid(): # check if form is valid or not
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            #authenticate the user against database using the authenticate() method
            if user is not None:
                if user.is_active:    #is_active is an attribute of django user model
                    login(request, user)
                    return HttpResponse('Authenticated '\
                                        'successfully')

                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid Login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})

#login_required decorator of the authentication framework.
@login_required
def dashboard(request):
    # display all actions by default
    actions = Action.objects.exclude(user=request.user)
    following_ids = request.user.following.values_list('id', flat=True)
    if following_ids:
        #if user is following others, retrieve only their actions
        actions = actions.filter(user_id__in=following_ids)    
    actions = actions.select_related('user', 'user_profile').prefetch_related('target')[:10] #select_related() allows to retrieve realted objects for one to many relationships
    #prefetch_related() works for many-to-many & many-to-one relations
    return render(request, 'account/dashboard.html', {'section': 'dashboard', 'actions': actions})

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # create a new user object but avoid saying it yet
            new_user = user_form.save(commit=False)
            #set the chosen password
            #set_password() method of user model that handles encrption to save for safety reasons.
            new_user.set_password(user_form.cleaned_data['password'])
            #save the user object
            new_user.save()
            Profile.objects.create(user=new_user)  #create the user profile
            create_action(new_user, 'has created an account')
            return render(request, 'account/register_done.html', {'new_user': new_user})

    else:
        user_form = UserRegistrationForm()
    return render(request, 'account/register.html', {'user_form': user_form})

@login_required  #login_required decorator because users have to be authenticated to edit their	profile.
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            # add a	success	message	when the user successfully updates their profile.
            messages.success(request, 'Profile updated successfully')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(request, 'account/edit.html', {'user_form': user_form, 'profile_form': profile_form})

@login_required
def user_list(request):  # to get all active users
    users = User.objects.filter(is_active=True)
    return render(request, 'account/user/list.html', {'section': 'people', 'users': users})

@login_required
def user_detail(request, username):  # to retrieve the active user with given username
    user = get_object_or_404(User, username=username, is_active=True)
    return render(request, 'account/user/detail.html', {'section': 'people', 'user': user})
    
@ajax_required
@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(user_from=request.user, user_to=user)
                create_action(request.user, 'is following', user)
            else:
                Contact.objects.filter(user_from=request.user, user_to=user).delete()
            return JsonResponse({'status':'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status':'ko'})
    return JsonResponse({'status':'ko'})


account/templates/base.html
<!-- base template for the website -->
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static "css/base.css" %}" rel="stylesheet">
    </head>
    <body>
        <div id="header">
            <span class="logo">Bookmarks</span>
            {% if request.user.is_authenticated %}
            <ul class="menu">
                <li {% if section == "dashboard" %} class="selected" {% endif %}>
                    <a href="{% url "dashboard" %}">My dashboard</a>
                </li>
                <li {% if section == "images" %} class="selected" {% endif %}>
                    <a href="{% url "images:list" %}">Images</a>
                </li>
                <li {% if section == "people" %} class="selected" {% endif %}>
                    <a href="{% url "user_list" %}">People</a>
                </li>
            </ul>
            {% endif %}

            <span class="user">
                {% if request.user.is_authenticated %}
                Hello {{ request.user.first_name }}
                <a href="{% url "logout" %}">Logout</a>

                {% else %}
                <a href="{% url "login" %}">Log-in</a>
                {% endif %}
            </span>
        </div>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li class="{{ message.tags }}">
                {{ message|safe }}
                <a href="#" class="close">x</a>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
        </script>
        <!-- script for loading js cookie plugin frm public CDN so we can interact with cookies-->
        <script	src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js">
        </script>
        <script>
            var csrftoken = Cookies.get('csrftoken');  //read value of csrftoken cookie with cookies.get()
            // function to check whether an http method is safe or not
            function csrfSafeMethod(method){  
                //these HTTP methods do not require csrf protection 
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({ //set jquery ajax requests using a $.ajaxSetUp()
                beforeSend: function(xhr, settings){
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain);
                }
            }
            });
        </script>
        <script>
            $(document).ready(function()
            {
                {% block domready %}
                {% endblock %}
            });
        </script>
    </body>
</html>